name: Static Analyze
run-name: ${{ github.actor }} analyzing ${{ github.ref }}

on:
  pull_request:
    branches:
      - main

env: # environment variables (available in any part of the action)
  NODE_VERSION: 20

jobs: # list of things to do
  linting:
    name: Linting # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Create .env
        run: echo '${{ toJSON(secrets) }}' | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> .env

      - name: Audit for vulnerabilities
        run: npx audit-ci@^6 --config ./audit-ci.jsonc

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Code prettify
        run: pnpm run format:ci

      - name: Build validation
        run: pnpm run build